
import type { AppProps } from "next/app";
import { AuthProvider } from '@/app/context/AuthContext/authProvider';
import 'bulma/css/bulma.css'
import '@/Styles/global.css'
import Head from "next/head";



export default function App({ Component, pageProps }: AppProps) {
  return (

    <AuthProvider>
      <Head> <title>Alan Godoy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/icons/logo_48x48.png "/></Head>

      <Component {...pageProps} />
    </AuthProvider>

  );
}
