export { Layout } from './layout'
export { CustomButton } from './common/customButton'
export { CadastroAlunos } from './Escola'
export { CadastroUsuarios } from './usuario'
export { HomeEscolaMusica } from './Escola'
export { MarcarReposicao } from './Escola'
export { VisualizarReposicoes } from './Escola'
export { ProgressoAlunos } from './Escola'
export { GerenciamentoInstrumentos } from './Escola'
export { GerenciamentoConteudo } from './Escola'
export { GerenciamentoProfessores } from './Escola'
export { GerenciamentoMensalidades } from './Escola'
export { ControleFinanceiro } from './Escola'
export { GerenciamentoAlunos } from './Escola'
export { GerenciamentoUsuarios } from './usuario'
export { LoginPage } from './usuario'
export { Modal } from './common/modal'
export { AgendaPage } from './Escola'
export { HomeInstitutoMusica } from './home-instituto'
export { HomeLoja } from './loja/home'
export { DashboardVendas} from './loja/venda/dashboard'
export {CadastroProduto} from './loja/produto/cadastro-produto'
export {GerenciamentoEstoque} from './loja/produto/controle-estoque'
export {GerenciamentoVendas} from './loja/venda/gerenciamento'
export {NovaVenda} from './loja/venda/formulario-venda'
export { CadastroCliente }  from './servicos-musicais/cliente/cadastro-cliente'
export { useNotification} from './common/notificacao/hookNotify'
export { ControleFinanceiroLoja} from './loja/receita'
export { useNotifications} from './common/notificacao/hookNotify/usoSimples'
export { DashboardServicosMusicais} from './servicos-musicais/servicos/dashboard'
export { GerenciamentoClientesPage } from './servicos-musicais/cliente/gerenciamento'
export { RealizacaoPedidoPage } from './servicos-musicais/pedido'
export { GerenciamentoPedidosPage } from './servicos-musicais/pedido/gerenciamento'
export { ControleFinanceiroServicos } from './servicos-musicais/receita'
export {NovoServicePage} from './servicos-musicais/servicos/cadastrar-servicos'
export {GerenciamentoCategoriasPage} from './servicos-musicais/servicos/categoria-servico'
export {HomeServicos} from './servicos-musicais/home'
export { GerenciamentoFornecedores} from './loja/produto/fornecedor'
export { Card } from '../components/common/metricaComponent'
export {ModalGenerico} from '../components/common/modal/modal-generico'
export { } from './common'
export { } from './usuario'

